### ISSUE TITLE
Uniquely identifying devices

### ISSUE THREAD

**Issue by Kestanous** [buildhybrid/device#1]
Hi there, was going to pop into your chat to ask but It was locked. Mind opening it up?

I was wondering what kind of testing you have done with this so far? I have heard that iPhones now do not share their uuid for example. 

I am looking for a way to to uniquely identify a device so I can see which ones the user is currently logged into and even log out devices. The aim is one logged in device per user at any time.

**Comment by andrewreedy** [comment]
@Kestanous Hey dude sorry I changed the name of the org so it threw Gitter off. We use this in production for logging devices let me check. Feel free to pop in the new gitter too.

**Comment by andrewreedy** [comment]
Yea iphone uuid seem to be working fine for us

**Comment by Kestanous** [comment]
@andrewreedy sorry I lost track of this! Awesome that is good to hear, I will have to try this package shortly then. If I find any issue I will let you know, closing until then.
